# 統計的仮設検定

<!-- auto-explain -->
### 解析環境の準備

このセルでは数値計算・分布計算に必要なライブラリを読み込みます。

モデル式:
$$\bar{x}=\frac{1}{n}\sum_{i=1}^{n}x_i,\quad s^2=\frac{1}{n-1}\sum_{i=1}^{n}(x_i-\bar{x})^2$$

In [17]:
import numpy as np
import pandas as pd
from scipy import stats

%precision 3

'%.3f'

<!-- auto-explain -->
### データ読み込みと標本モデル

このセルではデータを読み込み、標本として扱います（先頭行: # statistical_analysis_with_python/data/ch11_potato.csv）。

モデル式:
$$X_1,\dots,X_n \overset{i.i.d.}{\sim} F,\quad n=\text{sample size}$$

In [18]:
# statistical_analysis_with_python/data/ch11_potato.csv
df = pd.read_csv('/home/jovyan/data/ch11_potato.csv')
sample = np.array(df['重さ'])
sample

array([122.02, 131.73, 130.6 , 131.82, 132.05, 126.12, 124.43, 132.89,
       122.79, 129.95, 126.14, 134.45, 127.64, 125.68])

<!-- auto-explain -->
### 標本平均の計算

このセルでは標本平均を計算し、母平均の点推定値を求めます。

モデル式:
$$\hat{\mu}=\bar{x}=\frac{1}{n}\sum_{i=1}^{n}x_i$$

In [19]:
s_mean = np.mean(sample)
s_mean

128.451

## 11.1 統計的仮設検定とは
### 11.1.1. 統計的仮設検定の基本

<!-- auto-explain -->
### 正規分布にもとづく臨界値・p値計算

このセルでは標準化統計量と正規分布の分位点を使って判定境界またはp値を求めます。

モデル式:
$$Z=\frac{\bar{X}-\mu_0}{\sigma/\sqrt{n}}\sim\mathcal{N}(0,1)$$

In [20]:
rv = stats.norm(130, np.sqrt(9/14))
rv.isf(0.95)

128.681

<!-- auto-explain -->
### このセルの計算とモデル

このセルではサンプルから統計量を計算し、検定または推定に利用します。

モデル式:
$$T = \frac{\hat{\theta}-\theta_0}{SE(\hat{\theta})}$$

In [21]:
z = (s_mean - 130) / np.sqrt(9/14)
z

-1.932

<!-- auto-explain -->
### 正規分布にもとづく臨界値・p値計算

このセルでは標準化統計量と正規分布の分位点を使って判定境界またはp値を求めます。

モデル式:
$$Z=\frac{\bar{X}-\mu_0}{\sigma/\sqrt{n}}\sim\mathcal{N}(0,1)$$

In [22]:
rv = stats.norm()
rv.isf(0.95)

-1.645

<!-- auto-explain -->
### 正規分布にもとづく臨界値・p値計算

このセルでは標準化統計量と正規分布の分位点を使って判定境界またはp値を求めます。

モデル式:
$$Z=\frac{\bar{X}-\mu_0}{\sigma/\sqrt{n}}\sim\mathcal{N}(0,1)$$

In [23]:
rv.cdf(z)

0.027

### 11.1.2 片側検定と両側検定

<!-- auto-explain -->
### このセルの計算とモデル

このセルではサンプルから統計量を計算し、検定または推定に利用します。

モデル式:
$$T = \frac{\hat{\theta}-\theta_0}{SE(\hat{\theta})}$$

In [24]:
z = (s_mean - 130) / np.sqrt(9/14)
z

-1.932

<!-- auto-explain -->
### 正規分布にもとづく臨界値・p値計算

このセルでは標準化統計量と正規分布の分位点を使って判定境界またはp値を求めます。

モデル式:
$$Z=\frac{\bar{X}-\mu_0}{\sigma/\sqrt{n}}\sim\mathcal{N}(0,1)$$

In [25]:
rv = stats.norm()
rv.interval(0.95)

(-1.960, 1.960)

<!-- auto-explain -->
### 正規分布にもとづく臨界値・p値計算

このセルでは標準化統計量と正規分布の分位点を使って判定境界またはp値を求めます。

モデル式:
$$Z=\frac{\bar{X}-\mu_0}{\sigma/\sqrt{n}}\sim\mathcal{N}(0,1)$$

In [26]:
rv.cdf(z) * 2

0.053

### 11.1.3 仮設検定における2つの過誤

<!-- auto-explain -->
### 正規分布にもとづく臨界値・p値計算

このセルでは標準化統計量と正規分布の分位点を使って判定境界またはp値を求めます。

モデル式:
$$Z=\frac{\bar{X}-\mu_0}{\sigma/\sqrt{n}}\sim\mathcal{N}(0,1)$$

In [27]:
rv = stats.norm(130, 3)

<!-- auto-explain -->
### 正規分布にもとづく臨界値・p値計算

このセルでは標準化統計量と正規分布の分位点を使って判定境界またはp値を求めます。

モデル式:
$$Z=\frac{\bar{X}-\mu_0}{\sigma/\sqrt{n}}\sim\mathcal{N}(0,1)$$

In [28]:
c = stats.norm().isf(0.95)
n_samples = 10000
cnt = 0
for _ in range(n_samples):
    sample_ = np.round(rv.rvs(14), 2)
    s_mean_ = np.mean(sample_)
    z = (s_mean_ - 130) / np.sqrt(9/14)
    if z < c:
        cnt += 1
cnt / n_samples

0.051

<!-- auto-explain -->
### 正規分布にもとづく臨界値・p値計算

このセルでは標準化統計量と正規分布の分位点を使って判定境界またはp値を求めます。

モデル式:
$$Z=\frac{\bar{X}-\mu_0}{\sigma/\sqrt{n}}\sim\mathcal{N}(0,1)$$

In [29]:
rv = stats.norm(128, 3)

<!-- auto-explain -->
### 正規分布にもとづく臨界値・p値計算

このセルでは標準化統計量と正規分布の分位点を使って判定境界またはp値を求めます。

モデル式:
$$Z=\frac{\bar{X}-\mu_0}{\sigma/\sqrt{n}}\sim\mathcal{N}(0,1)$$

In [30]:
c = stats.norm().isf(0.95)
n_samples = 10000
cnt = 0
for _ in range(n_samples):
    sample_ = np.round(rv.rvs(14), 2)
    s_mean_ = np.mean(sample_)
    z = (s_mean_ - 130) / np.sqrt(9 / 14)
    if z >= c:
        cnt += 1
cnt / n_samples

0.198

## 11.2 基本的な仮設検定
### 11.2.1 正規分布の母平均の検定(母分散既知)

<!-- auto-explain -->
### 正規分布にもとづく臨界値・p値計算

このセルでは標準化統計量と正規分布の分位点を使って判定境界またはp値を求めます。

モデル式:
$$Z=\frac{\bar{X}-\mu_0}{\sigma/\sqrt{n}}\sim\mathcal{N}(0,1)$$

In [32]:
def pmean_test(sample, mean0, p_var, alpha=0.05):
    s_mean = np.mean(sample)
    n = len(sample)
    rv = stats.norm()
    interval = rv.interval(1 - alpha)

    z = (s_mean - mean0) / np.sqrt(p_var / n)
    if interval[0] <= z < interval[1]:
        print('帰無仮説を採択')
    else:
        print('帰無仮説を棄却')
    if z < 0:
        p = rv.cdf(z) * 2
    else:
        p = (1 - rv.cdf(z)) * 2
    print(f'p値は{p:.3f}')

<!-- auto-explain -->
### このセルの計算とモデル

このセルではサンプルから統計量を計算し、検定または推定に利用します。

モデル式:
$$T = \frac{\hat{\theta}-\theta_0}{SE(\hat{\theta})}$$

In [33]:
pmean_test(sample, 130, 9)

帰無仮説を採択
p値は0.053

### 11.2.2 正規分布の母分散の検定

<!-- auto-explain -->
### 正規分布にもとづく臨界値・p値計算

このセルでは標準化統計量と正規分布の分位点を使って判定境界またはp値を求めます。

モデル式:
$$Z=\frac{\bar{X}-\mu_0}{\sigma/\sqrt{n}}\sim\mathcal{N}(0,1)$$

In [34]:
def pvar_test(sample, var0, alpha=0.05):
    u_var = np.var(sample, ddof=1)
    n = len(sample)
    rv = stats.chi2(n - 1)
    interval = rv.interval(1 - alpha)

    y = (n - 1) * u_var / var0
    if interval[0] <= y < interval[1]:
        print('帰無仮説を採択')
    else:
        print('帰無仮説を棄却')
    if y < rv.isf(0.5):
        p = rv.cdf(y) * 2
    else:
        p = (1 - rv.cdf(y)) * 2
    print(f'p値は{p:.3f}')

<!-- auto-explain -->
### 分散またはカイ二乗統計量の計算

このセルでは分散に関する統計量を計算し、母分散の検定や適合度評価に使います。

モデル式:
$$Y=\frac{(n-1)S^2}{\sigma_0^2} \sim \chi^2_{n-1}$$

In [35]:
pvar_test(sample, 9)

帰無仮説を採択
p値は0.085

### 11.2.3 正規分布の母平均検定(母分散未知)

<!-- auto-explain -->
### 正規分布にもとづく臨界値・p値計算

このセルでは標準化統計量と正規分布の分位点を使って判定境界またはp値を求めます。

モデル式:
$$Z=\frac{\bar{X}-\mu_0}{\sigma/\sqrt{n}}\sim\mathcal{N}(0,1)$$

In [36]:
def pmean_test(sample, mean0, alpha=0.05):
    s_mean = np.mean(sample)
    u_var = np.var(sample, ddof=1)
    n = len(sample)
    rv = stats.t(n - 1)
    interval = rv.interval(1 - alpha)

    t = (s_mean - mean0) / np.sqrt(u_var / n)
    if interval[0] <= t < interval[1]:
        print('帰無仮説を採択')
    else:
        print('帰無仮説を棄却')
    if t < 0:
        p = rv.cdf(t) * 2
    else:
        p = (1 - rv.cdf(t)) * 2
    print(f'p値は{p:.3f}')

<!-- auto-explain -->
### このセルの計算とモデル

このセルではサンプルから統計量を計算し、検定または推定に利用します。

モデル式:
$$T = \frac{\hat{\theta}-\theta_0}{SE(\hat{\theta})}$$

In [38]:
pmean_test(sample, 130)

帰無仮説を採択
p値は0.169

<!-- auto-explain -->
### t検定統計量の計算

このセルでは平均差に対するt検定を実行し、帰無仮説を検証します。

モデル式:
$$t=\frac{\bar{x}-\mu_0}{s/\sqrt{n}},\quad p=2\min\{P(T\le t),P(T\ge t)\}$$

In [39]:
t, p = stats.ttest_1samp(sample, 130)
t, p

(-1.455, 0.169)

## 11.3 2標本問題に関する仮設検定
### 11.3.1 対応のあるt検定

<!-- auto-explain -->
### データ読み込みと標本モデル

このセルではデータを読み込み、標本として扱います（先頭行: # statistical_analysis_with_python/data/ch11_training_rel.csv）。

モデル式:
$$X_1,\dots,X_n \overset{i.i.d.}{\sim} F,\quad n=\text{sample size}$$

In [42]:
# statistical_analysis_with_python/data/ch11_training_rel.csv
training_rel = pd.read_csv('/home/jovyan/data/ch11_training_rel.csv')
print(training_rel.shape)
training_rel.head()

(20, 2)

    前   後
0  59  41
1  52  63
2  55  68
3  61  59
4  59  84

<!-- auto-explain -->
### このセルの計算とモデル

このセルではサンプルから統計量を計算し、検定または推定に利用します。

モデル式:
$$T = \frac{\hat{\theta}-\theta_0}{SE(\hat{\theta})}$$

In [43]:
training_rel['差'] = training_rel['後'] - training_rel['前']
training_rel.head()

    前   後   差
0  59  41 -18
1  52  63  11
2  55  68  13
3  61  59  -2
4  59  84  25

<!-- auto-explain -->
### t検定統計量の計算

このセルでは平均差に対するt検定を実行し、帰無仮説を検証します。

モデル式:
$$t=\frac{\bar{x}-\mu_0}{s/\sqrt{n}},\quad p=2\min\{P(T\le t),P(T\ge t)\}$$

In [45]:
t, p = stats.ttest_1samp(training_rel['差'], 0)
p

0.040

<!-- auto-explain -->
### t検定統計量の計算

このセルでは平均差に対するt検定を実行し、帰無仮説を検証します。

モデル式:
$$t=\frac{\bar{x}-\mu_0}{s/\sqrt{n}},\quad p=2\min\{P(T\le t),P(T\ge t)\}$$

In [46]:
t, p = stats.ttest_rel(training_rel['前'], training_rel['後'])
p

0.040

### 11.3.2 対応のないt検定

<!-- auto-explain -->
### データ読み込みと標本モデル

このセルではデータを読み込み、標本として扱います（先頭行: training_ind = pd.read_csv('/home/jovyan/data/ch11_training_ind.csv')）。

モデル式:
$$X_1,\dots,X_n \overset{i.i.d.}{\sim} F,\quad n=\text{sample size}$$

In [48]:
training_ind = pd.read_csv('/home/jovyan/data/ch11_training_ind.csv')
print(training_ind.shape)
training_ind.head()

(20, 2)

    A   B
0  47  49
1  50  52
2  37  54
3  60  48
4  39  51

<!-- auto-explain -->
### t検定統計量の計算

このセルでは平均差に対するt検定を実行し、帰無仮説を検証します。

モデル式:
$$t=\frac{\bar{x}-\mu_0}{s/\sqrt{n}},\quad p=2\min\{P(T\le t),P(T\ge t)\}$$

In [49]:
t, p = stats.ttest_ind(training_ind['A'], training_ind['B'], equal_var=False)
p

0.087

### 11.3.3 ウィルコクソンの符号付き順位検定

<!-- auto-explain -->
### データ読み込みと標本モデル

このセルではデータを読み込み、標本として扱います（先頭行: # statistical_analysis_with_python/data/ch11_training_rel.csv）。

モデル式:
$$X_1,\dots,X_n \overset{i.i.d.}{\sim} F,\quad n=\text{sample size}$$

In [50]:
# statistical_analysis_with_python/data/ch11_training_rel.csv
training_rel = pd.read_csv('/home/jovyan/data/ch11_training_rel.csv')
toy_df = training_rel[:6].copy()
toy_df

    前   後
0  59  41
1  52  63
2  55  68
3  61  59
4  59  84
5  45  37

<!-- auto-explain -->
### このセルの計算とモデル

このセルではサンプルから統計量を計算し、検定または推定に利用します。

モデル式:
$$T = \frac{\hat{\theta}-\theta_0}{SE(\hat{\theta})}$$

In [51]:
diff = toy_df['後'] - toy_df['前']
toy_df['差'] = diff
toy_df

    前   後   差
0  59  41 -18
1  52  63  11
2  55  68  13
3  61  59  -2
4  59  84  25
5  45  37  -8

<!-- auto-explain -->
### ウィルコクソン検定の順位計算

このセルでは差の絶対値に順位を付け、符号付き順位和を計算してノンパラメトリック検定を行います。

モデル式:
$$R_+=\sum_{d_i>0}\operatorname{rank}(|d_i|),\quad R_-=\sum_{d_i<0}\operatorname{rank}(|d_i|),\quad T=\min(R_+,R_-)$$

In [52]:
rank = stats.rankdata(abs(diff)).astype(int)
toy_df['順位'] = rank
toy_df

    前   後   差  順位
0  59  41 -18   5
1  52  63  11   3
2  55  68  13   4
3  61  59  -2   1
4  59  84  25   6
5  45  37  -8   2

<!-- auto-explain -->
### ウィルコクソン検定の順位計算

このセルでは差の絶対値に順位を付け、符号付き順位和を計算してノンパラメトリック検定を行います。

モデル式:
$$R_+=\sum_{d_i>0}\operatorname{rank}(|d_i|),\quad R_-=\sum_{d_i<0}\operatorname{rank}(|d_i|),\quad T=\min(R_+,R_-)$$

In [53]:
r_minus = np.sum((diff < 0) * rank)
r_plus = np.sum((diff > 0) * rank)
r_minus, r_plus

(np.int64(8), np.int64(13))

<!-- auto-explain -->
### ウィルコクソン検定の順位計算

このセルでは差の絶対値に順位を付け、符号付き順位和を計算してノンパラメトリック検定を行います。

モデル式:
$$R_+=\sum_{d_i>0}\operatorname{rank}(|d_i|),\quad R_-=\sum_{d_i<0}\operatorname{rank}(|d_i|),\quad T=\min(R_+,R_-)$$

In [54]:
toy_df['後'] = toy_df['前'] + np.arange(1, 7)
diff = toy_df['後'] - toy_df['前']
rank = stats.rankdata(abs(diff)).astype(int)
toy_df['差'] = diff
toy_df['順位'] = rank
toy_df

    前   後  差  順位
0  59  60  1   1
1  52  54  2   2
2  55  58  3   3
3  61  65  4   4
4  59  64  5   5
5  45  51  6   6

<!-- auto-explain -->
### ウィルコクソン検定の順位計算

このセルでは差の絶対値に順位を付け、符号付き順位和を計算してノンパラメトリック検定を行います。

モデル式:
$$R_+=\sum_{d_i>0}\operatorname{rank}(|d_i|),\quad R_-=\sum_{d_i<0}\operatorname{rank}(|d_i|),\quad T=\min(R_+,R_-)$$

In [56]:
r_minus = np.sum((diff < 0) * rank)
r_plus = np.sum((diff > 0) * rank)
r_minus, r_plus

(np.int64(0), np.int64(21))

<!-- auto-explain -->
### ウィルコクソン検定の順位計算

このセルでは差の絶対値に順位を付け、符号付き順位和を計算してノンパラメトリック検定を行います。

モデル式:
$$R_+=\sum_{d_i>0}\operatorname{rank}(|d_i|),\quad R_-=\sum_{d_i<0}\operatorname{rank}(|d_i|),\quad T=\min(R_+,R_-)$$

In [57]:
toy_df['後'] = toy_df['前'] + [1, -2, -3, 4, 5, -6]
diff = toy_df['後'] - toy_df['前']
rank = stats.rankdata(abs(diff)).astype(int)
toy_df['差'] = diff
toy_df['順位'] = rank
toy_df

    前   後  差  順位
0  59  60  1   1
1  52  50 -2   2
2  55  52 -3   3
3  61  65  4   4
4  59  64  5   5
5  45  39 -6   6

<!-- auto-explain -->
### ウィルコクソン検定の順位計算

このセルでは差の絶対値に順位を付け、符号付き順位和を計算してノンパラメトリック検定を行います。

モデル式:
$$R_+=\sum_{d_i>0}\operatorname{rank}(|d_i|),\quad R_-=\sum_{d_i<0}\operatorname{rank}(|d_i|),\quad T=\min(R_+,R_-)$$

In [58]:
r_minus = np.sum((diff < 0) * rank)
r_plus = np.sum((diff > 0) * rank)
r_minus, r_plus

(np.int64(11), np.int64(10))

<!-- auto-explain -->
### ウィルコクソン検定の順位計算

このセルでは差の絶対値に順位を付け、符号付き順位和を計算してノンパラメトリック検定を行います。

モデル式:
$$R_+=\sum_{d_i>0}\operatorname{rank}(|d_i|),\quad R_-=\sum_{d_i<0}\operatorname{rank}(|d_i|),\quad T=\min(R_+,R_-)$$

In [59]:
T, p = stats.wilcoxon(training_rel['前'], training_rel['後'])
p

0.038

<!-- auto-explain -->
### ウィルコクソン検定の順位計算

このセルでは差の絶対値に順位を付け、符号付き順位和を計算してノンパラメトリック検定を行います。

モデル式:
$$R_+=\sum_{d_i>0}\operatorname{rank}(|d_i|),\quad R_-=\sum_{d_i<0}\operatorname{rank}(|d_i|),\quad T=\min(R_+,R_-)$$

In [60]:
T, p = stats.wilcoxon(training_rel['後'], training_rel['前'])
p

0.038

<!-- auto-explain -->
### 正規分布にもとづく臨界値・p値計算

このセルでは標準化統計量と正規分布の分位点を使って判定境界またはp値を求めます。

モデル式:
$$Z=\frac{\bar{X}-\mu_0}{\sigma/\sqrt{n}}\sim\mathcal{N}(0,1)$$

In [61]:
n = 10000
diffs = np.round(stats.norm(3, 4).rvs(size=(n, 20)))

<!-- auto-explain -->
### t検定統計量の計算

このセルでは平均差に対するt検定を実行し、帰無仮説を検証します。

モデル式:
$$t=\frac{\bar{x}-\mu_0}{s/\sqrt{n}},\quad p=2\min\{P(T\le t),P(T\ge t)\}$$

In [65]:
cnt = 0
alpha = 0.05
for diff in diffs:
    t, p = stats.ttest_1samp(diff, 0)
    if p < alpha:
        cnt += 1
cnt / n

0.884

<!-- auto-explain -->
### ウィルコクソン検定の順位計算

このセルでは差の絶対値に順位を付け、符号付き順位和を計算してノンパラメトリック検定を行います。

モデル式:
$$R_+=\sum_{d_i>0}\operatorname{rank}(|d_i|),\quad R_-=\sum_{d_i<0}\operatorname{rank}(|d_i|),\quad T=\min(R_+,R_-)$$

In [66]:
cnt = 0
alpha = 0.05
for diff in diffs:
    t, p = stats.wilcoxon(diff, 0)
    if p < alpha:
        cnt += 1
cnt / n

0.872

### 11.3.4 マン・ホイットニーのU検定

<!-- auto-explain -->
### データ読み込みと標本モデル

このセルではデータを読み込み、標本として扱います（先頭行: training_ind = pd.read_csv('/home/jovyan/data/ch11_training_ind.csv')）。

モデル式:
$$X_1,\dots,X_n \overset{i.i.d.}{\sim} F,\quad n=\text{sample size}$$

In [67]:
training_ind = pd.read_csv('/home/jovyan/data/ch11_training_ind.csv')
toy_df = training_ind[:5].copy()
toy_df

    A   B
0  47  49
1  50  52
2  37  54
3  60  48
4  39  51

<!-- auto-explain -->
### ウィルコクソン検定の順位計算

このセルでは差の絶対値に順位を付け、符号付き順位和を計算してノンパラメトリック検定を行います。

モデル式:
$$R_+=\sum_{d_i>0}\operatorname{rank}(|d_i|),\quad R_-=\sum_{d_i<0}\operatorname{rank}(|d_i|),\quad T=\min(R_+,R_-)$$

In [68]:
rank = stats.rankdata(np.concatenate([toy_df['A'], toy_df['B']]))
rank_df = pd.DataFrame({'A': rank[:5], 'B': rank[5:10]}).astype(int)
rank_df

    A  B
0   3  5
1   6  8
2   1  9
3  10  4
4   2  7

<!-- auto-explain -->
### マン・ホイットニーU統計量の計算

このセルでは2群を併合して順位付けし、U統計量により分布差を検定します。

モデル式:
$$U=R_1-\frac{n_1(n_1+1)}{2}$$

In [69]:
n1 = len(toy_df['A'])
u = rank_df['A'].sum() - (n1 * (n1 + 1)) / 2
u

7.000

<!-- auto-explain -->
### このセルの計算とモデル

このセルではサンプルから統計量を計算し、検定または推定に利用します。

モデル式:
$$T = \frac{\hat{\theta}-\theta_0}{SE(\hat{\theta})}$$

In [70]:
rank_df = pd.DataFrame(np.arange(1, 11).reshape(2, 5).T, columns=['A', 'B'])
rank_df

   A   B
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

<!-- auto-explain -->
### マン・ホイットニーU統計量の計算

このセルでは2群を併合して順位付けし、U統計量により分布差を検定します。

モデル式:
$$U=R_1-\frac{n_1(n_1+1)}{2}$$

In [71]:
u = rank_df['A'].sum() - (n1 * (n1 + 1)) / 2
u

0.000

<!-- auto-explain -->
### このセルの計算とモデル

このセルではサンプルから統計量を計算し、検定または推定に利用します。

モデル式:
$$T = \frac{\hat{\theta}-\theta_0}{SE(\hat{\theta})}$$

In [72]:
rank_df = pd.DataFrame(np.arange(1, 11).reshape(2, 5)[::-1].T, columns=['A', 'B'])
rank_df

    A  B
0   6  1
1   7  2
2   8  3
3   9  4
4  10  5

<!-- auto-explain -->
### マン・ホイットニーU統計量の計算

このセルでは2群を併合して順位付けし、U統計量により分布差を検定します。

モデル式:
$$U=R_1-\frac{n_1(n_1+1)}{2}$$

In [73]:
u = rank_df['A'].sum() - (n1 * (n1 + 1)) / 2
u

25.000

<!-- auto-explain -->
### マン・ホイットニーU統計量の計算

このセルでは2群を併合して順位付けし、U統計量により分布差を検定します。

モデル式:
$$U=R_1-\frac{n_1(n_1+1)}{2}$$

In [75]:
u, p = stats.mannwhitneyu(training_ind['A'], training_ind['B'], alternative='two-sided')
p

0.059

### 11.3.5 カイ２乗検定

<!-- auto-explain -->
### データ読み込みと標本モデル

このセルではデータを読み込み、標本として扱います（先頭行: ad_df = pd.read_csv('/home/jovyan/data/ch11_ad.csv')）。

モデル式:
$$X_1,\dots,X_n \overset{i.i.d.}{\sim} F,\quad n=\text{sample size}$$

In [76]:
ad_df = pd.read_csv('/home/jovyan/data/ch11_ad.csv')
n = len(ad_df)
print(n)
ad_df.head()

1000

  広告     購入
0  B  しなかった
1  B  しなかった
2  A     した
3  A     した
4  B  しなかった

<!-- auto-explain -->
### 分割表とカイ二乗検定

このセルでは分割表の観測度数と期待度数を用いて独立性を検定します。

モデル式:
$$\chi^2=\sum_{i,j}\frac{(O_{ij}-E_{ij})^2}{E_{ij}},\quad E_{ij}=\frac{(\text{row}_i)(\text{col}_j)}{n}$$

In [77]:
ad_cross = pd.crosstab(ad_df['広告'], ad_df['購入'])
ad_cross

購入  した  しなかった
広告
A   49    351
B   51    549

<!-- auto-explain -->
### このセルの計算とモデル

このセルではサンプルから統計量を計算し、検定または推定に利用します。

モデル式:
$$T = \frac{\hat{\theta}-\theta_0}{SE(\hat{\theta})}$$

In [78]:
ad_cross['した'] / (ad_cross['した'] + ad_cross['しなかった'])

広告
A    0.1225
B    0.0850
dtype: float64

<!-- auto-explain -->
### このセルの計算とモデル

このセルではサンプルから統計量を計算し、検定または推定に利用します。

モデル式:
$$T = \frac{\hat{\theta}-\theta_0}{SE(\hat{\theta})}$$

In [79]:
n_yes, n_not = ad_cross.sum()
n_yes, n_not

(100, 900)

<!-- auto-explain -->
### このセルの計算とモデル

このセルではサンプルから統計量を計算し、検定または推定に利用します。

モデル式:
$$T = \frac{\hat{\theta}-\theta_0}{SE(\hat{\theta})}$$

In [80]:
n_adA, n_adB = ad_cross.sum(axis=1)
n_adA, n_adB

(400, 600)

<!-- auto-explain -->
### 分割表とカイ二乗検定

このセルでは分割表の観測度数と期待度数を用いて独立性を検定します。

モデル式:
$$\chi^2=\sum_{i,j}\frac{(O_{ij}-E_{ij})^2}{E_{ij}},\quad E_{ij}=\frac{(\text{row}_i)(\text{col}_j)}{n}$$

In [81]:
ad_ef = pd.DataFrame({'した': [n_adA * n_yes / n,
                             n_adB * n_yes / n],
                    'しなかった': [n_adA * n_not / n,
                                n_adB * n_not / n]}, 
                    index=['A', 'B'])
ad_ef

     した  しなかった
A  40.0  360.0
B  60.0  540.0

<!-- auto-explain -->
### 分割表とカイ二乗検定

このセルでは分割表の観測度数と期待度数を用いて独立性を検定します。

モデル式:
$$\chi^2=\sum_{i,j}\frac{(O_{ij}-E_{ij})^2}{E_{ij}},\quad E_{ij}=\frac{(\text{row}_i)(\text{col}_j)}{n}$$

In [82]:
y = ((ad_cross - ad_ef) ** 2 / ad_ef).sum().sum()
y

3.750

<!-- auto-explain -->
### 分散またはカイ二乗統計量の計算

このセルでは分散に関する統計量を計算し、母分散の検定や適合度評価に使います。

モデル式:
$$Y=\frac{(n-1)S^2}{\sigma_0^2} \sim \chi^2_{n-1}$$

In [83]:
rv = stats.chi2(1)
rv.sf(y)

0.053

<!-- auto-explain -->
### 分割表とカイ二乗検定

このセルでは分割表の観測度数と期待度数を用いて独立性を検定します。

モデル式:
$$\chi^2=\sum_{i,j}\frac{(O_{ij}-E_{ij})^2}{E_{ij}},\quad E_{ij}=\frac{(\text{row}_i)(\text{col}_j)}{n}$$

In [84]:
chi2, p, dof, ef = stats.chi2_contingency(ad_cross, correction=False)
chi2, p,dof

(3.750, 0.053, 1)

<!-- auto-explain -->
### このセルの計算とモデル

このセルではサンプルから統計量を計算し、検定または推定に利用します。

モデル式:
$$T = \frac{\hat{\theta}-\theta_0}{SE(\hat{\theta})}$$

In [85]:
ef

array([[ 40., 360.],
       [ 60., 540.]])

<!-- auto-explain -->
### 追加入力用セル

このセルは未記入です。今後の検定手順を追記できます。

モデル式:
$$T = \frac{\hat{\theta}-\theta_0}{SE(\hat{\theta})}$$